{% macro py2dep() -%}
  - python=2.7
  - pathlib2
{% endmacro -%}
{% macro py3dep() -%}
  - python>=3.6
{% endmacro -%}
name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - -e .
    - python-dotenv>=0.5.1
  - setuptools
  - wheel
  - sphinx
  - click
  - coverage
  - pytest-cov
  - jupyter
  - joblib
  - pandas
{% if cookiecutter.python_interpreter == 'python3' -%}
{{ py3dep()|indent(2, true) }}
{% else -%}
{{ py2dep()|indent(2, true) }}
{% endif -%}
